//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_PetShopEntities1 : DbContext
    {
        public QL_PetShopEntities1()
            : base("name=QL_PetShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblBinhLuan> tblBinhLuan { get; set; }
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public DbSet<tblChiTietHoaDonDichVu> tblChiTietHoaDonDichVu { get; set; }
        public DbSet<tblDanhMuc> tblDanhMuc { get; set; }
        public DbSet<tblDichVu> tblDichVu { get; set; }
        public DbSet<tblHinhAnh> tblHinhAnh { get; set; }
        public DbSet<tblHoaDon> tblHoaDon { get; set; }
        public DbSet<tblHoaDonDichVu> tblHoaDonDichVu { get; set; }
        public DbSet<tblKhachHang> tblKhachHang { get; set; }
        public DbSet<tblMaGiamGia> tblMaGiamGia { get; set; }
        public DbSet<tblNhaCungCap> tblNhaCungCap { get; set; }
        public DbSet<tblNhanVien> tblNhanVien { get; set; }
        public DbSet<tblSanPham> tblSanPham { get; set; }
        public DbSet<tblTinhTrang> tblTinhTrang { get; set; }
        public DbSet<tblTonKho> tblTonKho { get; set; }
        public DbSet<tblVaiTro> tblVaiTro { get; set; }
    }
}
