//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDonDichVu
    {
        public int MaHDDV { get; set; }
        public int MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaDichVu { get; set; }
    
        public virtual tblDichVu tblDichVu { get; set; }
        public virtual tblHoaDonDichVu tblHoaDonDichVu { get; set; }
    }
}
