//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDichVu
    {
        public tblDichVu()
        {
            this.tblChiTietHoaDonDichVu = new HashSet<tblChiTietHoaDonDichVu>();
        }
    
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaDichVu { get; set; }
    
        public virtual ICollection<tblChiTietHoaDonDichVu> tblChiTietHoaDonDichVu { get; set; }
    }
}
