//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhMuc
    {
        public tblDanhMuc()
        {
            this.tblSanPham = new HashSet<tblSanPham>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<tblSanPham> tblSanPham { get; set; }
    }
}
