//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonDichVu
    {
        public tblHoaDonDichVu()
        {
            this.tblChiTietHoaDonDichVu = new HashSet<tblChiTietHoaDonDichVu>();
        }
    
        public int MaHDDV { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<tblChiTietHoaDonDichVu> tblChiTietHoaDonDichVu { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
