//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        public tblHoaDon()
        {
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public Nullable<bool> DaThanhToan { get; set; }
        public string MaGiamGia { get; set; }
        public Nullable<decimal> TienGiam { get; set; }
    
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblMaGiamGia tblMaGiamGia { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblTinhTrang tblTinhTrang { get; set; }
    }
}
