//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaGiamGia
    {
        public tblMaGiamGia()
        {
            this.tblHoaDon = new HashSet<tblHoaDon>();
        }
    
        public string MaGiamGia { get; set; }
        public Nullable<decimal> PhanTramGiam { get; set; }
        public Nullable<decimal> SoTienGiamToiDa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual ICollection<tblHoaDon> tblHoaDon { get; set; }
    }
}
