//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        public tblSanPham()
        {
            this.tblBinhLuan = new HashSet<tblBinhLuan>();
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
            this.tblHinhAnh = new HashSet<tblHinhAnh>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string LoaiSanPham { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MauSac { get; set; }
        public string TinhTrangSucKhoe { get; set; }
        public string TienSuBenh { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        public virtual ICollection<tblBinhLuan> tblBinhLuan { get; set; }
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual tblDanhMuc tblDanhMuc { get; set; }
        public virtual ICollection<tblHinhAnh> tblHinhAnh { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblTonKho tblTonKho { get; set; }
    }
}
