//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVaiTro
    {
        public tblVaiTro()
        {
            this.tblNhanVien = new HashSet<tblNhanVien>();
        }
    
        public int IDVaiTro { get; set; }
        public string TenVaiTro { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<tblNhanVien> tblNhanVien { get; set; }
    }
}
